/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.teliacompany.toolbox.model;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum SeverityType { 
  STOP, DISTURBANCE, INFO  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"SeverityType\",\"namespace\":\"com.teliacompany.toolbox.model\",\"symbols\":[\"STOP\",\"DISTURBANCE\",\"INFO\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
