/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.teliacompany.toolbox.model;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum TicketType { 
  ACUTE, PLANNED, AUTO  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"TicketType\",\"namespace\":\"com.teliacompany.toolbox.model\",\"symbols\":[\"ACUTE\",\"PLANNED\",\"AUTO\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
